# Generated by Django 4.2.2 on 2023-07-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('rsLib', '0003_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AddField(
            model_name='users',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
