# Generated by Django 4.2.2 on 2023-08-01 06:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rsLib', '0009_issuedbook_issuerequest_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='issued_date',
        ),
        migrations.RemoveField(
            model_name='issuerequest',
            name='issued',
        ),
        migrations.AddField(
            model_name='issuedbook',
            name='issued_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='issuerequest',
            name='requested_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issuedbook',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='issuerequest',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
